name: Ionic Build for Android and iOS

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  setup:
    runs-on: macos-10.15
    steps:
    - name: Install Ionic CLI and then NPM Install
      run: |
        npm install -g @ionic/cli
        npm install
