name: Ionic Build for Android and iOS

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: NPM Install
      run: npm install

    - name: Add Android platform
      run: ionic cordova platform add android

    - name: Prepare Android platform
      run: ionic cordova prepare android

    - name: Build Android app
      run: ionic cordova build android

    - name: Add iOS platform
      run: ionic cordova platform add iOS

    - name: Prepare iOS platform
      run: ionic cordova prepare ios

    - name: Build iOS app
      run: ionic cordova build iOS
